// /lib/scholarshipData.js
// Central scholarship data for all countries — used by main page + slug pages

export const SCHOLARSHIP_RULES = {
  "united-states": {
    name: "United States",
    flag: "🇺🇸",
    continent: "North America",
    currency: "USD",
    language: "English",
    topUniversities: ["Harvard", "MIT", "Stanford", "Yale", "Columbia"],
    totalScholarships: "8,000+",
    avgAward: "USD 25,000–60,000/year",
    popularity: 98,
    types: {
      "fully-funded": {
        label: "Fully Funded Scholarships",
        examples: ["Fulbright", "Hubert Humphrey", "Gates Cambridge"],
        coverage: "Tuition + living + airfare + stipend",
        deadline: "October–December",
        competition: "Extremely High",
        gpa: "3.7+ / CGPA 3.5+",
        ielts: "7.0+",
        openTo: "Graduate, Research",
      },
      "partial": {
        label: "Partial / Merit Scholarships",
        examples: ["University Merit Awards", "Departmental Grants", "Assistantships"],
        coverage: "50–100% tuition",
        deadline: "January–March",
        competition: "High",
        gpa: "3.3+",
        ielts: "6.5+",
        openTo: "Undergraduate, Graduate",
      },
      "government": {
        label: "US Government Scholarships",
        examples: ["Fulbright Foreign Student", "USAID Scholarships", "Humphrey Fellowship"],
        coverage: "Full program cost",
        deadline: "September–November",
        competition: "Very High",
        gpa: "3.5+",
        ielts: "7.0+",
        openTo: "Graduate, Professional",
      },
      "need-based": {
        label: "Need-Based Financial Aid",
        examples: ["CSS Profile Aid", "University Financial Aid", "Foundation Grants"],
        coverage: "Variable — based on demonstrated need",
        deadline: "January–February",
        competition: "Moderate",
        gpa: "3.0+",
        ielts: "6.5+",
        openTo: "Undergraduate",
      },
    },
    popularScholarships: [
      { name: "Fulbright Foreign Student Program", fund: "Fully Funded", deadline: "Oct–Dec", level: "Graduate" },
      { name: "Gates-Cambridge Scholarship", fund: "Fully Funded", deadline: "October", level: "Graduate/PhD" },
      { name: "Hubert Humphrey Fellowship", fund: "Fully Funded", deadline: "October", level: "Professional" },
      { name: "AAUW International Fellowship", fund: "USD 18,000–30,000", deadline: "November", level: "Graduate" },
      { name: "Joint Japan/World Bank Scholarship", fund: "Fully Funded", deadline: "April", level: "Graduate" },
    ],
    requirements: [
      "Strong academic record (CGPA 3.5+ recommended for competitive programs)",
      "IELTS 6.5–7.5 or TOEFL 90–110+ depending on program",
      "GRE/GMAT scores required for most graduate programs",
      "2–3 letters of recommendation from academic or professional referees",
      "Statement of Purpose (SOP) — 500–1000 words, program-specific",
      "Research proposal (for PhD and research scholarships)",
      "Demonstrated leadership and community involvement",
      "Financial need documentation (for need-based aid)",
    ],
    tips: [
      "Start applications 12–18 months before your intended start date",
      "Apply to 8–12 universities to maximize your chances",
      "Contact potential PhD supervisors directly before submitting applications",
      "Tailor your SOP specifically to each university and program",
      "Register with the US Fulbright Commission in your country early",
      "Assistantships (TA/RA) are the most accessible funding path for graduates",
      "US universities consider holistic profiles — extracurriculars matter significantly",
    ],
    faqs: [
      {
        q: "Can Bangladeshi students get fully funded scholarships to study in the USA?",
        a: "Yes. Bangladeshi students are eligible for the Fulbright Foreign Student Program, Hubert Humphrey Fellowship, and many university-specific fellowships. Competitiveness is high, but Bangladeshi students regularly receive funding, especially in STEM, public policy, and development fields.",
      },
      {
        q: "Is GRE required for US scholarships?",
        a: "Many US graduate programs and scholarship committees require GRE scores. However, post-COVID, many institutions made GRE optional or dropped it permanently. Always check specific program requirements. For Fulbright, GRE is not universally required but strengthens the application.",
      },
      {
        q: "What is the difference between a scholarship and a fellowship in the US?",
        a: "A scholarship typically covers tuition and sometimes living costs for academic study. A fellowship often covers living expenses, research costs, and professional development in addition to tuition, and may require project deliverables or reporting. Fulbright and Humphrey are fellowships; university merit awards are scholarships.",
      },
      {
        q: "How do US university teaching assistantships work?",
        a: "Teaching Assistantships (TAs) provide full or partial tuition waivers plus a monthly stipend (typically USD 1,200–2,500) in exchange for teaching or research duties (15–20 hrs/week). They are the most common way international graduate students fund their education in the USA.",
      },
    ],
    relatedLinks: [
      { label: "UK Scholarships Guide", slug: "united-kingdom" },
      { label: "Canada Scholarships Guide", slug: "canada" },
      { label: "Australia Scholarships Guide", slug: "australia" },
      { label: "Germany Scholarships Guide", slug: "germany" },
    ],
  },

  "united-kingdom": {
    name: "United Kingdom",
    flag: "🇬🇧",
    continent: "Europe",
    currency: "GBP",
    language: "English",
    topUniversities: ["Oxford", "Cambridge", "Imperial", "UCL", "LSE"],
    totalScholarships: "5,000+",
    avgAward: "GBP 15,000–30,000/year",
    popularity: 95,
    types: {
      "fully-funded": {
        label: "Fully Funded Scholarships",
        examples: ["Chevening", "Commonwealth", "Gates-Cambridge"],
        coverage: "Tuition + living + airfare + visa",
        deadline: "November",
        competition: "Extremely High",
        gpa: "Upper Second Class (2:1) equivalent",
        ielts: "7.0+",
        openTo: "Graduate (Masters)",
      },
      "partial": {
        label: "University Scholarships & Bursaries",
        examples: ["Oxford Clarendon", "Edinburgh Global", "Bristol Think Big"],
        coverage: "£5,000–£15,000 per year",
        deadline: "January–March",
        competition: "High",
        gpa: "2:1 equivalent",
        ielts: "6.5+",
        openTo: "Undergraduate, Graduate",
      },
      "government": {
        label: "British Government Scholarships",
        examples: ["Chevening Scholarship", "Commonwealth Scholarship", "British Council Grants"],
        coverage: "Fully funded",
        deadline: "November",
        competition: "Very High",
        gpa: "Strong academic record",
        ielts: "7.0+",
        openTo: "Graduate",
      },
      "research": {
        label: "PhD & Research Funding",
        examples: ["UKRI Studentship", "Wellcome Trust", "Russell Group PhD Funding"],
        coverage: "Tuition + stipend (~£18,000/year)",
        deadline: "Year-round",
        competition: "High",
        gpa: "First Class / High 2:1",
        ielts: "7.0+",
        openTo: "PhD, Research",
      },
    },
    popularScholarships: [
      { name: "Chevening Scholarship", fund: "Fully Funded", deadline: "November", level: "Masters" },
      { name: "Commonwealth Scholarship", fund: "Fully Funded", deadline: "December", level: "Masters/PhD" },
      { name: "Gates-Cambridge Scholarship", fund: "Fully Funded", deadline: "October", level: "Graduate/PhD" },
      { name: "Oxford Clarendon Scholarship", fund: "Tuition + £18,180 stipend", deadline: "January", level: "Graduate/PhD" },
      { name: "British Council GREAT Scholarship", fund: "£10,000 minimum", deadline: "Varies", level: "Masters" },
    ],
    requirements: [
      "Minimum 2:1 (Upper Second Class) degree equivalent from a recognized university",
      "IELTS 6.5–7.0 (Chevening requires 6.5 overall with no band below 5.5)",
      "2–3 years of work experience (mandatory for Chevening; preferred for Commonwealth)",
      "3 references — at least 2 must be academic",
      "Personal statement / essay aligned to scholarship values",
      "Leadership potential and clear post-study return plan (for Chevening)",
      "Research proposal (for PhD, Commonwealth, and research awards)",
      "Valid passport and proof of citizenship of an eligible country",
    ],
    tips: [
      "Chevening deadline is November — prepare from June the year before",
      "Chevening requires demonstrated leadership — document all community roles clearly",
      "Commonwealth Scholarship favors candidates from developing Commonwealth nations",
      "Apply to the university admission first, then reference the offer in your scholarship application",
      "Gates-Cambridge is the most competitive UK scholarship — apply only with exceptional profiles",
      "Many Russell Group universities have automatic scholarship consideration upon admission",
      "Contact the Chevening alumni network in Bangladesh for guidance and mentorship",
    ],
    faqs: [
      {
        q: "What is the Chevening Scholarship and who is eligible from Bangladesh?",
        a: "Chevening is the UK Government's flagship scholarship, funded by the Foreign, Commonwealth and Development Office (FCDO). It offers fully funded one-year Master's degrees at any UK university. Bangladeshi citizens with a bachelor's degree, 2+ years work experience, and demonstrated leadership potential are eligible. The application opens in August and closes in November.",
      },
      {
        q: "Can I apply to multiple scholarships for the same UK university?",
        a: "Yes. You can apply for Chevening, Commonwealth, and university-specific scholarships simultaneously for the same program. Each has separate applications. If you receive multiple offers, you choose one. This is a recommended strategy to maximize your chances of funding.",
      },
      {
        q: "Does the Commonwealth Scholarship cover family members?",
        a: "Commonwealth Scholarships for Masters and PhDs include an allowance for dependants (spouse/children) joining you in the UK. This covers an initial arrival allowance and a monthly contribution toward dependent costs, though it does not cover the full cost of bringing family. Check specific award conditions as they vary by level.",
      },
      {
        q: "How competitive is the Chevening Scholarship for Bangladeshi applicants?",
        a: "Bangladesh is a high-competition Chevening country, receiving hundreds of applications annually. However, Bangladesh has a strong Chevening alumni network and consistent allocations. The key differentiators are authentic leadership narrative, clear study plan, and post-study impact vision rather than GPA alone.",
      },
    ],
    relatedLinks: [
      { label: "USA Scholarships Guide", slug: "united-states" },
      { label: "Canada Scholarships Guide", slug: "canada" },
      { label: "Australia Scholarships Guide", slug: "australia" },
      { label: "Schengen/Europe Scholarships", slug: "germany" },
    ],
  },

  canada: {
    name: "Canada",
    flag: "🇨🇦",
    continent: "North America",
    currency: "CAD",
    language: "English / French",
    topUniversities: ["UofT", "UBC", "McGill", "Waterloo", "McMaster"],
    totalScholarships: "4,500+",
    avgAward: "CAD 20,000–45,000/year",
    popularity: 92,
    types: {
      "fully-funded": {
        label: "Fully Funded Scholarships",
        examples: ["Vanier CGS", "Trudeau Foundation", "IDRC Awards"],
        coverage: "Tuition + CAD 50,000/year stipend",
        deadline: "November",
        competition: "Extremely High",
        gpa: "First class / A average",
        ielts: "7.0+",
        openTo: "PhD",
      },
      "government": {
        label: "Canadian Government Scholarships",
        examples: ["Vanier CGS", "Banting Fellowship", "SSHRC", "NSERC", "CIHR"],
        coverage: "Full funding including stipend",
        deadline: "October–November",
        competition: "Very High",
        gpa: "A average",
        ielts: "7.0+",
        openTo: "Graduate, PhD",
      },
      "partial": {
        label: "University & Provincial Awards",
        examples: ["Ontario Graduate Scholarship", "Alberta Graduate Excellence", "Quebec Bursaries"],
        coverage: "CAD 5,000–15,000",
        deadline: "February–April",
        competition: "Moderate–High",
        gpa: "B+ / 3.5+",
        ielts: "6.5+",
        openTo: "Graduate",
      },
      "research": {
        label: "Research Assistantships",
        examples: ["RA Positions", "Lab Funding", "MITACS Globalink"],
        coverage: "Stipend + tuition waiver",
        deadline: "Year-round",
        competition: "Moderate",
        gpa: "3.5+",
        ielts: "6.5+",
        openTo: "Graduate, PhD",
      },
    },
    popularScholarships: [
      { name: "Vanier Canada Graduate Scholarship", fund: "CAD 50,000/year (3 years)", deadline: "November", level: "PhD" },
      { name: "Trudeau Foundation Scholarship", fund: "CAD 40,000/year", deadline: "November", level: "PhD" },
      { name: "MITACS Globalink Research Award", fund: "CAD 6,000", deadline: "Rolling", level: "Undergraduate/Graduate" },
      { name: "Ontario Graduate Scholarship", fund: "CAD 10,000–15,000", deadline: "March", level: "Masters/PhD" },
      { name: "IDRC Research Awards", fund: "Fully Funded", deadline: "February", level: "Graduate/PhD" },
    ],
    requirements: [
      "First-class or high standing academic record (A average for most federal awards)",
      "IELTS 6.5–7.0 or TOEFL 90–100+",
      "Research proposal with clear methodology (for graduate scholarships)",
      "3 letters of recommendation — academic supervisors preferred",
      "Statement of interest / study plan",
      "Canadian supervisor/institution acceptance for research scholarships",
      "Demonstrated leadership and community engagement",
      "Publication or research experience (strongly preferred for Vanier, Banting)",
    ],
    tips: [
      "MITACS Globalink is one of the most accessible funding paths for South Asian students",
      "Secure a Canadian supervisor first — most research funding flows through them",
      "Provincial awards (Ontario, Alberta, BC) add significantly to federal funding",
      "Apply to at least 6–8 universities to maximize assistantship prospects",
      "Canadian universities strongly value research output — list all publications",
      "French proficiency opens additional funding through Quebec-specific programs",
      "NSERC/SSHRC/CIHR tri-council awards are the gold standard — aim for these at PhD level",
    ],
    faqs: [
      {
        q: "What is the MITACS Globalink Research Award for international students?",
        a: "MITACS Globalink provides a CAD 6,000 award for 12-week research internships at Canadian universities for current undergraduate or graduate students. It is one of the most accessible Canada-based research funding opportunities for South Asian students, including Bangladeshis. Applications open in September for the following summer.",
      },
      {
        q: "Is the Vanier CGS open to international students?",
        a: "Yes. The Vanier Canada Graduate Scholarships are open to both Canadian citizens and international students enrolled in Canadian PhD programs. The scholarship provides CAD 50,000 per year for 3 years. It is among the most prestigious doctoral scholarships in Canada and is extremely competitive.",
      },
      {
        q: "How do Canadian university Teaching Assistantships compare to US ones?",
        a: "Canadian TAs typically offer stipends of CAD 12,000–20,000 per year (vs USD 15,000–25,000 in the US) plus tuition waivers. The overall cost of living in Canada (outside Toronto/Vancouver) is often lower, making the net financial situation comparable or better. Processing times for study permits are also generally faster.",
      },
      {
        q: "Can I work while studying in Canada on a scholarship?",
        a: "Yes. International students in Canada with a valid study permit can work up to 20 hours per week during academic sessions and full-time during scheduled breaks without a separate work permit. This allows scholarship recipients to supplement their funding significantly. Post-graduation, a PGWP (up to 3 years) allows full-time work.",
      },
    ],
    relatedLinks: [
      { label: "USA Scholarships Guide", slug: "united-states" },
      { label: "UK Scholarships Guide", slug: "united-kingdom" },
      { label: "Australia Scholarships Guide", slug: "australia" },
      { label: "Germany Scholarships Guide", slug: "germany" },
    ],
  },

  australia: {
    name: "Australia",
    flag: "🇦🇺",
    continent: "Oceania",
    currency: "AUD",
    language: "English",
    topUniversities: ["ANU", "Melbourne", "Sydney", "UNSW", "Queensland"],
    totalScholarships: "3,500+",
    avgAward: "AUD 28,000–42,000/year",
    popularity: 89,
    types: {
      "fully-funded": {
        label: "Australia Awards (AAS)",
        examples: ["Australia Awards Scholarship", "Endeavour Leadership"],
        coverage: "Tuition + living + airfare + extras",
        deadline: "April–June",
        competition: "High",
        gpa: "CGPA 3.0+ / 60%+",
        ielts: "6.5+",
        openTo: "Graduate (Masters/PhD)",
      },
      "government": {
        label: "Australian Government Scholarships",
        examples: ["Australia Awards", "ARC Discovery", "NHMRC"],
        coverage: "Full cost including stipend",
        deadline: "April–May",
        competition: "High",
        gpa: "Strong academic record",
        ielts: "6.5+",
        openTo: "Graduate, PhD",
      },
      "university": {
        label: "University Excellence Awards",
        examples: ["Melbourne Graduate Research", "ANU Chancellor's", "UNSW Scientia"],
        coverage: "AUD 5,000–35,000",
        deadline: "October–February",
        competition: "Moderate–High",
        gpa: "Credit average / 3.5+",
        ielts: "6.5+",
        openTo: "Graduate",
      },
      "research": {
        label: "RTP Stipend (Research Training Program)",
        examples: ["RTP Fee Offset", "RTP Stipend", "University Top-Up"],
        coverage: "Tuition waiver + AUD 28,000–32,000/year",
        deadline: "Year-round",
        competition: "Moderate",
        gpa: "First Class Honours",
        ielts: "6.5+",
        openTo: "PhD",
      },
    },
    popularScholarships: [
      { name: "Australia Awards Scholarship (AAS)", fund: "Fully Funded", deadline: "April–June", level: "Masters/PhD" },
      { name: "Research Training Program (RTP)", fund: "Tuition + AUD 28,000–32,000/year", deadline: "Rolling", level: "PhD" },
      { name: "ANU Chancellor's International Scholarship", fund: "35% tuition reduction", deadline: "Rolling", level: "Graduate" },
      { name: "Melbourne Graduate Research Scholarship", fund: "Tuition + AUD 30,000/year", deadline: "October", level: "PhD" },
      { name: "Destination Australia Scholarship", fund: "AUD 15,000/year", deadline: "Varies", level: "All levels" },
    ],
    requirements: [
      "Minimum CGPA 3.0 or 60%+ (Australia Awards specific requirements vary by country)",
      "IELTS 6.5 overall (Australia Awards requires no band below 6.0)",
      "Professional or academic work experience (2+ years preferred for AAS)",
      "Two academic or professional referees",
      "Study and research plan / personal statement",
      "Evidence of ties to home country and return intention (for AAS)",
      "Health and character requirements for Australian student visa",
      "Demonstrated development impact potential (for AAS)",
    ],
    tips: [
      "Australia Awards favors candidates with rural/regional origin or public sector employment",
      "AAS applications open in April — prepare from January the same year",
      "RTP funding is automatic for PhD candidates at many Group of Eight universities",
      "Australian universities rank research output heavily — publications boost applications",
      "Living costs in regional cities (Adelaide, Canberra, Hobart) are significantly lower",
      "The 485 Post-Study Work visa gives 2–4 years post-graduation work rights",
      "ANU, Melbourne, and UNSW are the most internationally competitive for scholarships",
    ],
    faqs: [
      {
        q: "Who is eligible for the Australia Awards Scholarship from Bangladesh?",
        a: "Bangladeshi citizens who are not current Australian permanent residents or citizens are eligible. AAS targets developing country nationals. For Bangladesh, priority is given to candidates from government, public sector, NGOs, and academia who demonstrate potential to contribute to national development upon return. Minimum IELTS 6.5 and a bachelor's degree are baseline requirements.",
      },
      {
        q: "What is the Research Training Program (RTP) in Australia?",
        a: "The RTP is Australia's primary mechanism for funding international PhD students. It provides a tuition fee offset (covering 100% of tuition) and a living allowance stipend of approximately AUD 28,000–32,000 per year. Most Australian Group of Eight universities automatically award RTP to competitive PhD applicants. It does not require a separate application — it is embedded in the PhD admission process.",
      },
      {
        q: "How long does it take to get an Australia Awards Scholarship result?",
        a: "The Australia Awards Scholarship timeline for Bangladesh applicants runs from April (applications open) to approximately October–November (results announced) for the following year's intake. The process includes written application, interview rounds, and medical clearance. In total, expect 6–8 months from application to final confirmation.",
      },
      {
        q: "Can I bring my family to Australia on a research scholarship?",
        a: "Yes. PhD students on RTP scholarships (and some other awards) can bring family members. The primary student visa (Subclass 500) allows dependants (spouse and children) to accompany you. Dependants can study full-time and work without restriction. However, accommodation and family living costs must be self-funded unless the scholarship includes a dependant allowance.",
      },
    ],
    relatedLinks: [
      { label: "UK Scholarships Guide", slug: "united-kingdom" },
      { label: "New Zealand Scholarships", slug: "new-zealand" },
      { label: "Canada Scholarships Guide", slug: "canada" },
      { label: "Japan Scholarships Guide", slug: "japan" },
    ],
  },

  germany: {
    name: "Germany",
    flag: "🇩🇪",
    continent: "Europe",
    currency: "EUR",
    language: "German / English",
    topUniversities: ["TU Munich", "LMU Munich", "Heidelberg", "Humboldt", "KIT"],
    totalScholarships: "6,000+",
    avgAward: "EUR 850–1,200/month stipend",
    popularity: 88,
    types: {
      "fully-funded": {
        label: "DAAD Scholarships",
        examples: ["DAAD Development-Related Postgrad", "DAAD Research Grants", "Helmut Schmidt"],
        coverage: "Monthly stipend + tuition + insurance + travel",
        deadline: "October–November",
        competition: "High",
        gpa: "Very good / 3.5+",
        ielts: "6.5+ or German B2",
        openTo: "Graduate, PhD",
      },
      "government": {
        label: "German Government Funding",
        examples: ["DAAD Scholarships", "Erasmus+", "Heinrich Böll Foundation"],
        coverage: "EUR 750–1,200/month",
        deadline: "October–January",
        competition: "High",
        gpa: "Very good academic record",
        ielts: "6.5+",
        openTo: "Graduate, PhD",
      },
      "tuition-free": {
        label: "Tuition-Free Study",
        examples: ["Public University Programs", "State-Funded Programs", "English Masters"],
        coverage: "No tuition (only semester fee ~EUR 300)",
        deadline: "January–July",
        competition: "Moderate",
        gpa: "Good / 3.0+",
        ielts: "6.5+ or German B2",
        openTo: "Undergraduate, Graduate",
      },
      "research": {
        label: "PhD & Research Positions",
        examples: ["Paid PhD Positions", "Max Planck Institute", "Fraunhofer", "Helmholtz"],
        coverage: "EUR 1,400–2,200/month (employment contract)",
        deadline: "Year-round",
        competition: "Moderate–High",
        gpa: "Very good / First class",
        ielts: "6.0+",
        openTo: "PhD, Research",
      },
    },
    popularScholarships: [
      { name: "DAAD Development-Related Postgraduate Courses", fund: "Full stipend + tuition", deadline: "October–November", level: "Masters" },
      { name: "Helmut Schmidt Programme (DAAD)", fund: "EUR 850/month + extras", deadline: "November", level: "Masters" },
      { name: "Heinrich Böll Foundation Scholarship", fund: "EUR 850/month + EUR 300 study allowance", deadline: "March/September", level: "Graduate/PhD" },
      { name: "Konrad Adenauer Foundation Scholarship", fund: "EUR 850/month", deadline: "March", level: "Graduate/PhD" },
      { name: "Erasmus+ Scholarship", fund: "EUR 700–1,000/month", deadline: "Varies by institution", level: "All levels" },
    ],
    requirements: [
      "Bachelor's degree with strong academic standing (Very Good / 3.5+ equivalent)",
      "IELTS 6.5+ for English programs; German B2/C1 for German-taught programs",
      "APS Certificate (Academic Evaluation Centre) for Bangladeshi applicants",
      "Motivation letter (DAAD-specific format for development scholarships)",
      "Two academic references",
      "CV in German or English (Europass format preferred)",
      "Proof of acceptance or application to a German university program",
      "Research proposal (for PhD and research-oriented awards)",
    ],
    tips: [
      "Germany's public universities charge no tuition — only a semester fee (~EUR 300). This alone makes it exceptional value.",
      "DAAD scholarships open in October for the following academic year — prepare from July",
      "APS certification for Bangladeshis takes 4–8 weeks — start early",
      "German language skills open 90% more programs and significantly strengthen DAAD applications",
      "Paid PhD positions ('wissenschaftliche Mitarbeiter') are employment contracts, not scholarships — apply directly to professors",
      "DAAD Development scholarships specifically target candidates from developing countries — Bangladesh is well-positioned",
      "Living costs outside Munich and Frankfurt are very affordable (EUR 700–900/month total)",
    ],
    faqs: [
      {
        q: "Is the DAAD scholarship available for Bangladeshi students?",
        a: "Yes. Bangladesh is a priority country for DAAD's development-related scholarships. The DAAD Development-Related Postgraduate Courses (EPOS) program is specifically designed for candidates from developing nations who plan to return home and contribute to national development. Bangladeshi government employees, NGO professionals, and academics are particularly competitive applicants.",
      },
      {
        q: "Are German universities really tuition-free for international students?",
        a: "Public German universities charge no tuition fees to international students — the same as for German students. You only pay a semester contribution fee of approximately EUR 150–350, which includes a public transport pass and student union fees. Baden-Württemberg was an exception (charged EUR 1,500/semester for non-EU students) but reversed this policy. Private universities do charge tuition.",
      },
      {
        q: "What is an APS Certificate and why do Bangladeshi students need it?",
        a: "The APS (Akademische Prüfstelle / Academic Evaluation Centre) is a document authentication process operated by the German embassy in Dhaka. Bangladeshi students applying for German student visas or DAAD scholarships must submit their academic credentials to APS for verification. The process costs approximately EUR 150 and takes 4–8 weeks. It is mandatory and cannot be bypassed.",
      },
      {
        q: "Can I do a PhD in Germany without speaking German?",
        a: "Yes. Many German PhD programs — particularly at top research institutes like Max Planck, Helmholtz, and DFG-funded labs — operate entirely in English. Paid PhD positions in STEM fields are especially likely to be English-medium. However, learning German (at least A2–B1 level) significantly eases daily life and opens additional career opportunities in Germany.",
      },
    ],
    relatedLinks: [
      { label: "France Scholarships Guide", slug: "france" },
      { label: "Netherlands Scholarships", slug: "netherlands" },
      { label: "Schengen Area Overview", slug: "schengen" },
      { label: "UK Scholarships Guide", slug: "united-kingdom" },
    ],
  },

  japan: {
    name: "Japan",
    flag: "🇯🇵",
    continent: "Asia",
    currency: "JPY",
    language: "Japanese / English",
    topUniversities: ["UTokyo", "Kyoto", "Osaka", "Tohoku", "Nagoya"],
    totalScholarships: "3,000+",
    avgAward: "JPY 143,000–145,000/month stipend",
    popularity: 84,
    types: {
      "government": {
        label: "MEXT (Monbukagakusho) Scholarship",
        examples: ["MEXT Research Student", "MEXT Undergraduate", "MEXT Teacher Training"],
        coverage: "Full tuition + JPY 117,000–145,000/month + airfare",
        deadline: "May–July (Embassy) / November (University)",
        competition: "High",
        gpa: "3.5+ / 70%+",
        ielts: "Not required (Japanese skills advantageous)",
        openTo: "Undergraduate, Graduate, PhD",
      },
      "university": {
        label: "Japanese University Scholarships",
        examples: ["JASSO", "University Private Awards", "JICA Partner Scholarships"],
        coverage: "JPY 30,000–150,000/month",
        deadline: "Varies",
        competition: "Moderate",
        gpa: "3.0+",
        ielts: "6.0+",
        openTo: "Graduate",
      },
      "private": {
        label: "Private Foundation Scholarships",
        examples: ["Rotary Foundation", "Okazaki Kaheita", "Honda Foundation"],
        coverage: "JPY 80,000–180,000/month",
        deadline: "Year-round",
        competition: "Moderate–High",
        gpa: "3.0+",
        ielts: "Varies",
        openTo: "Graduate",
      },
      "research": {
        label: "Research Fellowships",
        examples: ["JSPS Fellowship", "RIKEN Research", "NII Internships"],
        coverage: "Full stipend + research cost",
        deadline: "Year-round",
        competition: "High",
        gpa: "First class",
        ielts: "Not required (research-focused)",
        openTo: "PhD, Research",
      },
    },
    popularScholarships: [
      { name: "MEXT Embassy Scholarship", fund: "Fully Funded + monthly stipend", deadline: "May–June", level: "Undergraduate/Graduate" },
      { name: "MEXT University Recommendation", fund: "Fully Funded + monthly stipend", deadline: "November", level: "Graduate" },
      { name: "JASSO Honors Scholarship", fund: "JPY 48,000/month", deadline: "After arrival", level: "All levels" },
      { name: "JSPS Research Fellowship (DC/PD)", fund: "JPY 150,000–200,000/month", deadline: "May", level: "PhD/Postdoc" },
      { name: "Rotary Peace Fellowship", fund: "Fully Funded", deadline: "November", level: "Masters" },
    ],
    requirements: [
      "Age limit for MEXT: under 35 years (graduate) or under 24 (undergraduate)",
      "CGPA 3.0+ or equivalent 65%+ academic record",
      "Japanese language proficiency (JLPT N2+ preferred; not required for English programs)",
      "IELTS 5.5–6.5 for English-medium programs",
      "Research plan in Japanese or English (for research scholarships)",
      "Two academic references",
      "Medical certificate of good health",
      "Letter of acceptance from a Japanese professor (university recommendation route)",
    ],
    tips: [
      "MEXT Embassy route: apply through the Japanese Embassy in Dhaka (opens May–June)",
      "MEXT University route: contact a Japanese professor first and secure their agreement",
      "Learning Japanese (even N3 level) significantly increases success with MEXT",
      "Private foundation scholarships are applied for after arrival in Japan — budget accordingly",
      "JSPS DC1/DC2 fellowships are the most prestigious for PhD students — apply in your first year",
      "Japanese universities value research alignment — professor match is critical",
      "JASSO scholarship applications are processed after you begin studying in Japan",
    ],
    faqs: [
      {
        q: "What is the MEXT scholarship and how does it work for Bangladeshi students?",
        a: "MEXT (Ministry of Education, Culture, Sports, Science and Technology) is Japan's government scholarship. It covers full tuition, round-trip airfare, and provides a monthly living stipend of approximately JPY 117,000–145,000. Bangladeshi students can apply through two routes: the Embassy Recommendation route (opens May, through Japanese Embassy in Dhaka) or the University Recommendation route (contact a Japanese professor who recommends you directly to MEXT).",
      },
      {
        q: "Do I need to know Japanese to study in Japan on a scholarship?",
        a: "Not necessarily. Many graduate programs — especially at the top Japanese universities — offer English-medium courses, and MEXT research students often work in English-speaking labs. However, Japanese proficiency (JLPT N2+) significantly strengthens MEXT applications and makes daily life much easier. A 6-month Japanese language training period is included in many MEXT scholarship programs before the main degree begins.",
      },
      {
        q: "How competitive is MEXT for Bangladeshi students?",
        a: "MEXT is highly competitive but Bangladesh has a historically strong allocation. Approximately 30–50 Bangladeshi students receive MEXT annually across all categories. Key factors are academic record, research alignment with the chosen professor/program, and motivation letter quality. The university recommendation route is often considered more competitive but also more reliable once a professor commits.",
      },
      {
        q: "Can I work part-time in Japan on a MEXT scholarship?",
        a: "Yes. MEXT scholarship holders can apply for permission to engage in activities outside their primary status (資格外活動許可). This allows work up to 28 hours per week during semesters and full-time during vacation periods. Many students work part-time (arubaito) to supplement their stipend, especially in Tokyo and Osaka where living costs are higher.",
      },
    ],
    relatedLinks: [
      { label: "South Korea Scholarships", slug: "south-korea" },
      { label: "China Scholarships Guide", slug: "china" },
      { label: "Singapore Scholarships", slug: "singapore" },
      { label: "Australia Scholarships Guide", slug: "australia" },
    ],
  },

  "south-korea": {
    name: "South Korea",
    flag: "🇰🇷",
    continent: "Asia",
    currency: "KRW",
    language: "Korean / English",
    topUniversities: ["SNU", "KAIST", "POSTECH", "Yonsei", "Korea University"],
    totalScholarships: "2,500+",
    avgAward: "KRW 900,000–1,200,000/month + tuition",
    popularity: 80,
    types: {
      "government": {
        label: "GKS (Global Korea Scholarship)",
        examples: ["GKS Undergraduate", "GKS Graduate", "GKS Research"],
        coverage: "Tuition + KRW 900,000–1,000,000/month + airfare + settlement",
        deadline: "February–March",
        competition: "High",
        gpa: "3.0+ (GKS requires 80%+)",
        ielts: "5.5+ or TOPIK",
        openTo: "Undergraduate, Graduate, PhD",
      },
      "university": {
        label: "Korean University Scholarships",
        examples: ["KAIST Fellowship", "POSTECH Scholarship", "SNU Graduate Scholarship"],
        coverage: "Full tuition + monthly stipend",
        deadline: "Varies",
        competition: "Moderate–High",
        gpa: "3.0+",
        ielts: "6.0+",
        openTo: "Graduate, PhD",
      },
      "research": {
        label: "Research-Based Funding",
        examples: ["NRF Fellowships", "Professor Lab Funding", "KOICA"],
        coverage: "Stipend + research costs",
        deadline: "Year-round",
        competition: "Moderate",
        gpa: "3.0+",
        ielts: "Varies",
        openTo: "PhD, Research",
      },
    },
    popularScholarships: [
      { name: "Global Korea Scholarship (GKS) Graduate", fund: "Fully Funded + KRW 1,000,000/month", deadline: "February–March", level: "Masters/PhD" },
      { name: "GKS Undergraduate (NIIED)", fund: "Fully Funded + KRW 900,000/month", deadline: "February", level: "Undergraduate" },
      { name: "KAIST Graduate Fellowship", fund: "Full tuition + KRW 300,000–500,000/month", deadline: "Rolling", level: "Graduate/PhD" },
      { name: "POSTECH Graduate Scholarship", fund: "Full tuition + monthly stipend", deadline: "Rolling", level: "Graduate/PhD" },
      { name: "Korean Government KOICA Fellowship", fund: "Fully Funded", deadline: "May", level: "Masters" },
    ],
    requirements: [
      "Academic record of 80%+ (GKS requirement) — CGPA 3.0+ equivalent",
      "Age: Under 40 for graduate GKS; Under 25 for undergraduate GKS",
      "TOPIK Level 3+ (for Korean-taught programs) or IELTS 5.5+ for English programs",
      "Research plan and study purpose statement",
      "Two academic references",
      "Medical certificate",
      "Nationality of a country with diplomatic relations with South Korea",
      "Cannot hold Korean citizenship or be a current Korean resident",
    ],
    tips: [
      "GKS applications open in February — register with NIIED portal early",
      "Korean language skills (even TOPIK 1) significantly strengthen GKS applications",
      "KAIST and POSTECH have the strongest automatic funding for graduate students",
      "Contact Korean professors by email before applying — lab funding is the easiest route",
      "Seoul living costs are high — regional universities like POSTECH (Pohang) offer much lower costs",
      "KOICA fellowship specifically targets government employees and development professionals",
      "GKS includes a 1-year Korean language training before your main degree program",
    ],
    faqs: [
      {
        q: "What is the GKS (Global Korea Scholarship) and how can Bangladeshis apply?",
        a: "GKS (formerly KGSP) is South Korea's government scholarship managed by the National Institute for International Education (NIIED). It offers full tuition, monthly allowance (~KRW 900,000–1,000,000), round-trip airfare, settlement allowance, language training, and medical insurance. Bangladeshi citizens can apply through the Embassy Recommendation track (via Korean Embassy in Dhaka, deadline February) or the University Recommendation track (through Korean universities directly).",
      },
      {
        q: "Is the GKS scholarship competitive for Bangladeshi applicants?",
        a: "Bangladesh has a moderate-to-high GKS allocation. Competition has increased significantly in recent years. A strong academic record (80%+ or CGPA 3.5+), clear research motivation, and some Korean language ability are the key differentiators. STEM fields and Korea-related research topics are particularly favored by the selection committee.",
      },
      {
        q: "Do Korean universities offer English-medium programs?",
        a: "Yes. Most top Korean universities offer graduate programs entirely in English, especially in engineering, business, and natural sciences at institutions like KAIST, POSTECH, SNU, and Yonsei. Undergraduate programs are predominantly in Korean, making the GKS undergraduate track more challenging without Korean language skills.",
      },
    ],
    relatedLinks: [
      { label: "Japan Scholarships Guide", slug: "japan" },
      { label: "China Scholarships Guide", slug: "china" },
      { label: "Singapore Scholarships", slug: "singapore" },
      { label: "USA Scholarships Guide", slug: "united-states" },
    ],
  },

  china: {
    name: "China",
    flag: "🇨🇳",
    continent: "Asia",
    currency: "CNY",
    language: "Chinese / English",
    topUniversities: ["Peking", "Tsinghua", "Fudan", "Zhejiang", "SJTU"],
    totalScholarships: "10,000+",
    avgAward: "CNY 3,500–3,500/month + tuition",
    popularity: 82,
    types: {
      "government": {
        label: "Chinese Government Scholarship (CSC)",
        examples: ["CSC Full Scholarship", "CSC Provincial Scholarship", "Belt & Road Scholarship"],
        coverage: "Tuition + CNY 3,000–3,500/month + accommodation",
        deadline: "February–April",
        competition: "Moderate–High",
        gpa: "3.0+",
        ielts: "Not required (Chinese or English medium)",
        openTo: "Undergraduate, Graduate, PhD",
      },
      "provincial": {
        label: "Provincial & University Awards",
        examples: ["Beijing Government Scholarship", "Shanghai Government Scholarship", "University Awards"],
        coverage: "Partial to full tuition + stipend",
        deadline: "March–June",
        competition: "Moderate",
        gpa: "2.8+",
        ielts: "Varies",
        openTo: "All levels",
      },
      "confucius": {
        label: "Confucius Institute Scholarship",
        examples: ["HANBAN Scholarship", "Confucius China Studies", "Chinese Language Teacher"],
        coverage: "Full tuition + CNY 2,500/month",
        deadline: "March",
        competition: "Moderate",
        gpa: "2.5+",
        ielts: "Not required",
        openTo: "All levels (language focus)",
      },
    },
    popularScholarships: [
      { name: "Chinese Government Scholarship (CSC)", fund: "Full tuition + CNY 3,500/month", deadline: "March–April", level: "All levels" },
      { name: "Belt and Road Scholarship", fund: "Full tuition + stipend", deadline: "March", level: "Graduate" },
      { name: "Confucius Institute Scholarship", fund: "Full tuition + CNY 2,500/month", deadline: "March", level: "All levels" },
      { name: "Beijing Government Scholarship", fund: "Full tuition + stipend", deadline: "May", level: "Graduate" },
      { name: "Tsinghua/Peking University Scholarship", fund: "Full or partial funding", deadline: "February", level: "Graduate" },
    ],
    requirements: [
      "CGPA 2.8+ (CSC is accessible to a wide range of academic backgrounds)",
      "No IELTS required for Chinese-medium programs; 5.5–6.0 for English programs",
      "Age: Under 45 for most CSC categories",
      "Physical examination form (CSC-specific medical form)",
      "Non-criminal record certificate",
      "Study or research plan in Chinese or English",
      "Two academic references",
      "Valid passport with at least 2 years validity",
    ],
    tips: [
      "CSC is the most accessible major government scholarship in the world — acceptance rate is relatively high",
      "Apply through both the CSC portal AND directly to Chinese universities for maximum chances",
      "Type A (university-nominated) CSC applications are more competitive but have higher success rates",
      "Mandarin proficiency (HSK 4+) dramatically expands available programs and quality of life",
      "Provincial scholarships (Shanghai, Beijing, Guangdong) add significantly to CSC funding",
      "English-medium programs at top Chinese universities are expanding rapidly",
      "Chinese universities process applications faster than most Western counterparts",
    ],
    faqs: [
      {
        q: "Is the Chinese Government Scholarship (CSC) easy to get for Bangladeshi students?",
        a: "CSC is considered more accessible than UK Chevening, US Fulbright, or Australian AAS. Bangladesh receives a moderate allocation annually. While it is not automatic, candidates with a solid academic record (60%+), a clear study plan, and a genuine interest in China-related academic work have reasonable chances. Applying through multiple channels (university-nominated + self-application) improves success rates.",
      },
      {
        q: "Can I study in China entirely in English?",
        a: "Yes. Major Chinese universities (Tsinghua, Peking, Fudan, SJTU, etc.) offer hundreds of programs taught entirely in English, particularly at the graduate level. However, daily life in China without Mandarin can be challenging. Many CSC recipients take Mandarin language courses during or before their program — these are often provided free of charge to scholarship holders.",
      },
      {
        q: "Does the CSC scholarship cover all costs?",
        a: "CSC full scholarships cover tuition fees, accommodation on-campus, and a monthly stipend (CNY 2,500–3,500 depending on study level). International flights are also reimbursed (one way or return, depending on the category). Out-of-pocket costs include food, personal expenses, books, and any off-campus housing if the student chooses not to live in the dormitory.",
      },
    ],
    relatedLinks: [
      { label: "Japan Scholarships Guide", slug: "japan" },
      { label: "South Korea Scholarships", slug: "south-korea" },
      { label: "Malaysia Scholarships", slug: "malaysia" },
      { label: "Germany Scholarships Guide", slug: "germany" },
    ],
  },

  turkey: {
    name: "Turkey",
    flag: "🇹🇷",
    continent: "Europe/Asia",
    currency: "TRY",
    language: "Turkish / English",
    topUniversities: ["Bogazici", "METU", "Istanbul Technical", "Hacettepe", "Bilkent"],
    totalScholarships: "2,000+",
    avgAward: "TRY 5,000–12,000/month + tuition",
    popularity: 76,
    types: {
      "government": {
        label: "Türkiye Bursları (Turkey Scholarships)",
        examples: ["Turkiye Burslari Full", "Research Scholarship", "Short Program"],
        coverage: "Full tuition + monthly stipend + accommodation + airfare",
        deadline: "February",
        competition: "Moderate–High",
        gpa: "3.0+ (undergraduate: 70%+, graduate: 75%+)",
        ielts: "Not required (Turkish or English programs)",
        openTo: "Undergraduate, Graduate, PhD",
      },
      "university": {
        label: "University Scholarships",
        examples: ["Bilkent Scholarship", "Sabanci Merit Award", "YTU Awards"],
        coverage: "Partial to full tuition",
        deadline: "Varies",
        competition: "Moderate",
        gpa: "3.0+",
        ielts: "6.0+",
        openTo: "All levels",
      },
    },
    popularScholarships: [
      { name: "Türkiye Bursları (Full Scholarship)", fund: "Fully Funded + monthly stipend", deadline: "February", level: "All levels" },
      { name: "Türkiye Bursları Research Scholarship", fund: "Fully Funded + stipend", deadline: "February", level: "PhD/Postdoc" },
      { name: "Bilkent University Scholarship", fund: "Full tuition", deadline: "Rolling", level: "Graduate" },
      { name: "Mevlana Exchange Program", fund: "Partial funding", deadline: "Varies", level: "All levels" },
    ],
    requirements: [
      "Academic record: 70%+ for undergraduate, 75%+ for masters, 75%+ for PhD",
      "Age: Under 30 for masters, under 35 for PhD",
      "Turkish language proficiency (preferred but not mandatory for English programs)",
      "IELTS 6.0+ for English-medium programs",
      "Motivation letter aligned to Türkiye Bursları values",
      "Two references",
      "Medical fitness certificate",
      "Valid passport",
    ],
    tips: [
      "Türkiye Bursları application opens in January and closes in February — be ready early",
      "Turkish language learning (even A2) significantly boosts application scores",
      "Turkey has excellent programs in engineering, medicine, architecture, and social sciences",
      "The scholarship covers private health insurance — a significant benefit",
      "Istanbul and Ankara have large Bangladeshi student communities for support",
      "Turkish degree is well-recognized in Muslim-majority countries and beyond",
    ],
    faqs: [
      {
        q: "What is Türkiye Bursları and how accessible is it for Bangladeshis?",
        a: "Türkiye Bursları (Turkey Scholarships) is one of the most generous government scholarships globally, covering full tuition, accommodation, monthly stipend, health insurance, and round-trip airfare. Bangladesh is an eligible country and receives a good allocation annually. The application process is entirely online through the official portal, and the competition is moderate compared to Western scholarships.",
      },
      {
        q: "Do I need to learn Turkish to study in Turkey on a scholarship?",
        a: "Not immediately. Türkiye Bursları includes a mandatory one-year Turkish language training before the main degree program begins. After this year, you study in Turkish (for Turkish-medium programs) or in English (for English-medium programs). Learning Turkish during the language year opens the full range of Turkish university programs.",
      },
    ],
    relatedLinks: [
      { label: "Germany Scholarships Guide", slug: "germany" },
      { label: "Malaysia Scholarships", slug: "malaysia" },
      { label: "China Scholarships Guide", slug: "china" },
      { label: "Japan Scholarships Guide", slug: "japan" },
    ],
  },

  malaysia: {
    name: "Malaysia",
    flag: "🇲🇾",
    continent: "Asia",
    currency: "MYR",
    language: "Malay / English",
    topUniversities: ["UM", "UPM", "UTM", "USM", "UKM"],
    totalScholarships: "1,500+",
    avgAward: "MYR 1,500–3,500/month",
    popularity: 71,
    types: {
      "government": {
        label: "Malaysian Government Scholarships",
        examples: ["MIS (Malaysia International Scholarship)", "Commonwealth Scholarship"],
        coverage: "Full tuition + MYR 2,500–3,500/month",
        deadline: "April–June",
        competition: "Moderate",
        gpa: "3.0+",
        ielts: "6.0+",
        openTo: "Graduate, PhD",
      },
      "university": {
        label: "University Research Scholarships",
        examples: ["UM Graduate Scholarship", "UTM Scholarship", "UPM Research Fellowship"],
        coverage: "Tuition waiver + MYR 1,500/month",
        deadline: "Rolling",
        competition: "Moderate",
        gpa: "3.0+",
        ielts: "5.5+",
        openTo: "Graduate, PhD",
      },
    },
    popularScholarships: [
      { name: "Malaysia International Scholarship (MIS)", fund: "Full tuition + MYR 3,000/month", deadline: "June", level: "Graduate/PhD" },
      { name: "Commonwealth Scholarship (Malaysia allocation)", fund: "Full funding", deadline: "December", level: "Masters" },
      { name: "UM Graduate Research Assistantship", fund: "Tuition + MYR 1,500/month", deadline: "Rolling", level: "PhD" },
    ],
    requirements: [
      "CGPA 3.0+ or equivalent",
      "IELTS 6.0+ or TOEFL 80+",
      "2 academic references",
      "Research proposal for graduate programs",
      "Malaysian university admission letter (for most awards)",
    ],
    tips: [
      "Malaysia is one of the most affordable English-speaking study destinations in Asia",
      "Malaysian universities are recognized across Islamic countries and Commonwealth nations",
      "MIS scholarship application opens in April via scholarship.mohe.gov.my",
      "Dual-track system: apply to university + MIS simultaneously",
      "Living costs in Kuala Lumpur are much lower than Singapore or Australian cities",
    ],
    faqs: [
      {
        q: "Is Malaysia a good destination for Bangladeshi scholarship students?",
        a: "Yes. Malaysia offers affordable tuition, English-medium programs, strong Islamic culture alignment, and easier visa processes for Bangladeshis. The Malaysia International Scholarship (MIS) is a government-funded award for developing nation students at the graduate level. Malaysia also serves as a strategic stepping stone for further migration to Singapore or Australia.",
      },
    ],
    relatedLinks: [
      { label: "Singapore Scholarships", slug: "singapore" },
      { label: "Japan Scholarships Guide", slug: "japan" },
      { label: "South Korea Scholarships", slug: "south-korea" },
      { label: "Australia Scholarships Guide", slug: "australia" },
    ],
  },

  "new-zealand": {
    name: "New Zealand",
    flag: "🇳🇿",
    continent: "Oceania",
    currency: "NZD",
    language: "English",
    topUniversities: ["Auckland", "Otago", "Victoria Wellington", "Canterbury", "Waikato"],
    totalScholarships: "800+",
    avgAward: "NZD 20,000–35,000/year",
    popularity: 68,
    types: {
      "government": {
        label: "New Zealand Government Scholarships",
        examples: ["NZ Aid Programme Scholarship", "Commonwealth Scholarship"],
        coverage: "Full tuition + living + airfare",
        deadline: "February–March",
        competition: "Moderate",
        gpa: "3.0+",
        ielts: "6.5+",
        openTo: "Graduate",
      },
      "university": {
        label: "University Excellence Scholarships",
        examples: ["Vice-Chancellor's Scholarship", "Doctoral Scholarship"],
        coverage: "Tuition waiver + NZD 25,000–28,000/year",
        deadline: "October–February",
        competition: "Moderate",
        gpa: "3.5+",
        ielts: "6.5+",
        openTo: "PhD",
      },
    },
    popularScholarships: [
      { name: "NZ Aid Programme Scholarship", fund: "Fully Funded", deadline: "February–March", level: "Masters" },
      { name: "University of Auckland Doctoral Scholarship", fund: "Tuition + NZD 27,500/year", deadline: "Rolling", level: "PhD" },
      { name: "Otago Doctoral Scholarship", fund: "Tuition + NZD 25,000/year", deadline: "Rolling", level: "PhD" },
    ],
    requirements: [
      "CGPA 3.0+ or equivalent",
      "IELTS 6.5+",
      "Research proposal for doctoral programs",
      "2 academic references",
      "NZ Aid: demonstrated development sector experience preferred",
    ],
    tips: [
      "New Zealand is among the safest and most livable countries for international students",
      "Post-study work visa of 1–3 years is available depending on program length",
      "NZ Aid targets Pacific and developing nation candidates — Bangladesh is eligible",
      "Living costs in cities like Dunedin and Hamilton are significantly lower than Auckland",
    ],
    faqs: [
      {
        q: "Does New Zealand offer post-study work rights?",
        a: "Yes. Graduates of eligible New Zealand programs can apply for a Post-Study Work Visa of 1–3 years depending on the level of study completed. This is a significant benefit for Bangladeshi graduates looking to gain international work experience.",
      },
    ],
    relatedLinks: [
      { label: "Australia Scholarships Guide", slug: "australia" },
      { label: "Canada Scholarships Guide", slug: "canada" },
      { label: "UK Scholarships Guide", slug: "united-kingdom" },
    ],
  },

  singapore: {
    name: "Singapore",
    flag: "🇸🇬",
    continent: "Asia",
    currency: "SGD",
    language: "English",
    topUniversities: ["NUS", "NTU", "SMU", "SUTD", "SIT"],
    totalScholarships: "1,200+",
    avgAward: "SGD 1,500–2,500/month + tuition",
    popularity: 78,
    types: {
      "government": {
        label: "Singapore Government Scholarships",
        examples: ["SINGA", "A*STAR", "NRF Fellowships"],
        coverage: "Full tuition + SGD 2,000–2,500/month",
        deadline: "June / December",
        competition: "Very High",
        gpa: "3.5+",
        ielts: "6.5+",
        openTo: "PhD, Research",
      },
      "university": {
        label: "NUS/NTU Research Scholarship",
        examples: ["NUS Research Scholarship", "NTU Presidential Graduate Fellowship", "SMU Fellowship"],
        coverage: "Full tuition + SGD 1,800–2,200/month",
        deadline: "Rolling",
        competition: "High",
        gpa: "3.5+",
        ielts: "6.5+",
        openTo: "PhD",
      },
    },
    popularScholarships: [
      { name: "SINGA (A*STAR Singapore) Scholarship", fund: "Full tuition + SGD 2,000/month + allowances", deadline: "June / December", level: "PhD" },
      { name: "NUS Research Scholarship", fund: "Full tuition + SGD 2,000/month", deadline: "Rolling", level: "PhD" },
      { name: "NTU Presidential Graduate Fellowship", fund: "Full tuition + SGD 2,200/month", deadline: "Rolling", level: "PhD" },
    ],
    requirements: [
      "Extremely strong academic record (First Class Honours or equivalent)",
      "Research publications or significant lab experience strongly recommended",
      "IELTS 6.5+ or TOEFL 100+",
      "GRE scores may be required for certain programs",
      "3 academic references from senior researchers",
      "Research proposal and alignment with faculty interests",
    ],
    tips: [
      "Singapore scholarships are among the most competitive in Asia — target if you have publications",
      "NUS and NTU rank in the global top 15 — the degree itself is highly valuable",
      "Living in Singapore is expensive — ensure stipend calculations cover actual costs",
      "SINGA includes all living costs and provides a relocation allowance",
      "Contact NUS/NTU professors before applying — direct lab funding is the most reliable path",
    ],
    faqs: [
      {
        q: "Is Singapore a realistic scholarship destination for average Bangladeshi students?",
        a: "Singapore scholarships are highly competitive and primarily target PhD-level researchers with strong publication records. For Masters students, self-funded enrollment is more common. However, exceptional candidates with strong CGPA (3.7+), research experience, and relevant lab skills are competitive for NUS/NTU research scholarships.",
      },
    ],
    relatedLinks: [
      { label: "Japan Scholarships Guide", slug: "japan" },
      { label: "Australia Scholarships Guide", slug: "australia" },
      { label: "South Korea Scholarships", slug: "south-korea" },
      { label: "Malaysia Scholarships", slug: "malaysia" },
    ],
  },

  france: {
    name: "France",
    flag: "🇫🇷",
    continent: "Europe",
    currency: "EUR",
    language: "French / English",
    topUniversities: ["Sorbonne", "PSL", "Polytechnique", "Sciences Po", "ENS"],
    totalScholarships: "3,000+",
    avgAward: "EUR 700–1,100/month",
    popularity: 74,
    types: {
      "government": {
        label: "French Government Scholarships",
        examples: ["Excellence-Major Scholarship", "Eiffel Scholarship", "Campus France Award"],
        coverage: "EUR 1,067/month + tuition exemption + insurance",
        deadline: "January–February",
        competition: "High",
        gpa: "Excellent / top of class",
        ielts: "Not required (French programs); 6.5+ (English)",
        openTo: "Graduate, PhD",
      },
      "erasmus": {
        label: "Erasmus+ & EU Scholarships",
        examples: ["Erasmus Mundus", "Horizon Europe", "Marie Curie"],
        coverage: "EUR 700–1,000/month + tuition",
        deadline: "October–January",
        competition: "High",
        gpa: "3.5+",
        ielts: "6.0+",
        openTo: "Graduate, PhD",
      },
    },
    popularScholarships: [
      { name: "Eiffel Excellence Scholarship", fund: "EUR 1,067/month + full benefits", deadline: "January", level: "Masters/PhD" },
      { name: "Erasmus Mundus Joint Masters", fund: "EUR 24,000/year total", deadline: "January–February", level: "Masters" },
      { name: "Sciences Po Scholarship", fund: "Partial to full tuition", deadline: "March", level: "Graduate" },
      { name: "Région Île-de-France Scholarship", fund: "EUR 15,000–25,000", deadline: "Varies", level: "PhD" },
    ],
    requirements: [
      "Strong academic record (top of class for Eiffel; 3.5+ for most programs)",
      "French proficiency (DELF/DALF B2+) for French-medium programs",
      "IELTS 6.5+ for English-medium programs at French universities",
      "University nomination (for Eiffel — French institution must nominate you)",
      "Research proposal for PhD scholarships",
      "2–3 academic references",
      "Campus France pre-registration (for most scholarship applications)",
    ],
    tips: [
      "Eiffel is institution-nominated — contact French universities first",
      "French public universities charge minimal tuition (EUR 170–380) even without scholarships",
      "France is particularly strong in engineering, business, social sciences, and arts",
      "French language skills (B2+) open the vast majority of French university programs",
      "Erasmus Mundus programs combine study across multiple EU countries — excellent for career",
    ],
    faqs: [
      {
        q: "What is the Eiffel Excellence Scholarship and how do Bangladeshis apply?",
        a: "The Eiffel Scholarship is awarded by Campus France (French government) to outstanding international students. Bangladeshi students cannot apply directly — a French higher education institution must nominate you. The process is: (1) get admitted to a French university, (2) ask the international office to nominate you for Eiffel, (3) campus France evaluates the application. The monthly stipend is EUR 1,067 for Masters and EUR 1,400 for PhD.",
      },
    ],
    relatedLinks: [
      { label: "Germany Scholarships Guide", slug: "germany" },
      { label: "Netherlands Scholarships", slug: "netherlands" },
      { label: "UK Scholarships Guide", slug: "united-kingdom" },
    ],
  },

  netherlands: {
    name: "Netherlands",
    flag: "🇳🇱",
    continent: "Europe",
    currency: "EUR",
    language: "Dutch / English",
    topUniversities: ["Delft TU", "Amsterdam", "Leiden", "Utrecht", "Wageningen"],
    totalScholarships: "2,000+",
    avgAward: "EUR 10,000–25,000/year",
    popularity: 72,
    types: {
      "government": {
        label: "Holland Scholarship & StuNed",
        examples: ["Holland Scholarship", "StuNed (Indonesia focus)", "Orange Knowledge Programme"],
        coverage: "EUR 5,000–15,000",
        deadline: "February–March",
        competition: "Moderate–High",
        gpa: "3.0+",
        ielts: "6.5+",
        openTo: "Graduate",
      },
      "university": {
        label: "Dutch University Excellence Awards",
        examples: ["TU Delft Excellence Scholarship", "Leiden Scholarship", "Wageningen Scholarship"],
        coverage: "EUR 10,000–20,000",
        deadline: "January–February",
        competition: "Moderate",
        gpa: "3.5+",
        ielts: "6.5+",
        openTo: "Masters",
      },
    },
    popularScholarships: [
      { name: "Holland Scholarship", fund: "EUR 5,000 (one-time)", deadline: "February", level: "Masters" },
      { name: "TU Delft Excellence Scholarship", fund: "EUR 25,000 (full tuition)", deadline: "January", level: "Masters" },
      { name: "Orange Knowledge Programme", fund: "Full tuition + allowances", deadline: "March", level: "Masters/Short" },
      { name: "Erasmus Mundus at Dutch Universities", fund: "EUR 24,000/year", deadline: "January", level: "Masters" },
    ],
    requirements: [
      "CGPA 3.0+ or equivalent",
      "IELTS 6.5–7.0 (most Dutch programs require 6.5 minimum)",
      "University admission confirmation",
      "Motivation letter specific to Dutch institution",
      "2 academic references",
      "Orange Knowledge: 3+ years work experience, employer support letter",
    ],
    tips: [
      "Netherlands is the most English-friendly non-English-speaking country in Europe",
      "Almost all Dutch Masters programs are English-medium",
      "Orange Knowledge Programme (OKP) specifically targets developing nation professionals",
      "Holland Scholarship is competitive but widely available across Dutch universities",
      "Dutch universities have strong industry links — particularly valuable for engineering and business",
    ],
    faqs: [
      {
        q: "Is Bangladesh eligible for the Orange Knowledge Programme (OKP)?",
        a: "Yes. Bangladesh is on the Netherlands OKP priority country list. The scholarship targets mid-career professionals from development-priority countries for short courses and Masters programs at Dutch institutions. Applicants must have employer support and demonstrate how the study will benefit their work and home country.",
      },
    ],
    relatedLinks: [
      { label: "Germany Scholarships Guide", slug: "germany" },
      { label: "France Scholarships Guide", slug: "france" },
      { label: "UK Scholarships Guide", slug: "united-kingdom" },
    ],
  },
};

// ── SCHOLARSHIP TYPE META ──────────────────────────────────────────────────
export const SCHOLARSHIP_TYPE_META = {
  "fully-funded":   { label:"Fully Funded",       color:"bg-emerald-100 text-emerald-800 border-emerald-200", icon:"🏆" },
  "government":     { label:"Government Award",   color:"bg-blue-100 text-blue-800 border-blue-200",          icon:"🏛️" },
  "partial":        { label:"Partial Scholarship", color:"bg-amber-100 text-amber-800 border-amber-200",       icon:"📚" },
  "university":     { label:"University Award",   color:"bg-purple-100 text-purple-800 border-purple-200",    icon:"🎓" },
  "research":       { label:"Research Funding",   color:"bg-rose-100 text-rose-800 border-rose-200",          icon:"🔬" },
  "need-based":     { label:"Need-Based Aid",     color:"bg-slate-100 text-slate-800 border-slate-200",       icon:"🤝" },
  "tuition-free":   { label:"Tuition-Free",       color:"bg-teal-100 text-teal-800 border-teal-200",          icon:"🆓" },
  "erasmus":        { label:"Erasmus+",            color:"bg-indigo-100 text-indigo-800 border-indigo-200",    icon:"🇪🇺" },
  "confucius":      { label:"Confucius/HANBAN",    color:"bg-red-100 text-red-800 border-red-200",             icon:"🐉" },
  "provincial":     { label:"Provincial Award",   color:"bg-orange-100 text-orange-800 border-orange-200",    icon:"🗺️" },
  "private":        { label:"Private Foundation", color:"bg-pink-100 text-pink-800 border-pink-200",          icon:"💎" },
};

// ── CONTINENT GROUPS ──────────────────────────────────────────────────────
export const CONTINENTS = {
  "North America": ["united-states", "canada"],
  "Europe":        ["united-kingdom", "germany", "france", "netherlands", "turkey"],
  "Asia":          ["japan", "south-korea", "china", "singapore", "malaysia", "turkey"],
  "Oceania":       ["australia", "new-zealand"],
};

// ── SLUG HELPERS ───────────────────────────────────────────────────────────
export function makeScholarshipSlug(country) {
  return country.toLowerCase().replace(/\s+/g, "-");
}

export function getScholarshipData(slug) {
  return SCHOLARSHIP_RULES[slug] || null;
}